name: materialsDB
channels:
  - defaults
dependencies:
  - python=3.9
  - pip=23.3.1
  - pip:
    - pytest==7.3.1
    - Flask==3.0.0
    - Flask-Cors==3.0.10
    - Flask-Bootstrap==3.3.7.1
    - Flask-SQLAlchemy==3.1.1
    - gunicorn==20.1.0
    - psycopg2==2.9.3
    - SQLAlchemy==1.4.25
    - requests==2.26.0
    - lxml==4.6.3
    - numpy==1.21.2
    - pandas==1.3.3
    - yfinance==0.1.67
    - flask8==6.1.0
    - Black==23.10.1
    - pytest==7.4.3
    - toml==0.10.2
    - pytest-cov==4.1.0
