INSERT INTO Company(Location,Subsidiary,CompanyID,CompanyName) VALUES ('United States','Dow Inc.',0,'The Dow Chemical Company');
INSERT INTO Company(Location,Subsidiary,CompanyID,CompanyName) VALUES ('United States','DowDuPont Inc.',1,'DuPont');
INSERT INTO Company(Location,Subsidiary,CompanyID,CompanyName) VALUES ('United States','N/A',2,'3M');
INSERT INTO Company(Location,Subsidiary,CompanyID,CompanyName) VALUES ('Germany','N/A',3,'BASF');
INSERT INTO Company(Location,Subsidiary,CompanyID,CompanyName) VALUES ('United States','N/A',4,'Corning Incorporated');
INSERT INTO Company(Location,Subsidiary,CompanyID,CompanyName) VALUES ('United States','N/A',5,'Kimberly-Clark Corporation');
INSERT INTO Company(Location,Subsidiary,CompanyID,CompanyName) VALUES ('United States','N/A',6,'Owens Corning');
INSERT INTO Company(Location,Subsidiary,CompanyID,CompanyName) VALUES ('United States','N/A',7,'Sherwin-Williams');
INSERT INTO Company(Location,Subsidiary,CompanyID,CompanyName) VALUES ('United States','N/A',8,'Nucor Corporation');
INSERT INTO Company(Location,Subsidiary,CompanyID,CompanyName) VALUES ('United States','N/A',9,'PPG Industries');
INSERT INTO Company(Location,Subsidiary,CompanyID,CompanyName) VALUES ('United States','N/A',10,'Eastman Chemical Company');
INSERT INTO Company(Location,Subsidiary,CompanyID,CompanyName) VALUES ('France','N/A',11,'Air Liquide');
INSERT INTO Company(Location,Subsidiary,CompanyID,CompanyName) VALUES ('France','N/A',12,'Saint-Gobain');
INSERT INTO Company(Location,Subsidiary,CompanyID,CompanyName) VALUES ('United States','N/A',13,'International Paper');
INSERT INTO Company(Location,Subsidiary,CompanyID,CompanyName) VALUES ('United States','N/A',14,'Weyerhaeuser');
INSERT INTO Company(Location,Subsidiary,CompanyID,CompanyName) VALUES ('United States','N/A',15,'Ball Corporation');
INSERT INTO Company(Location,Subsidiary,CompanyID,CompanyName) VALUES ('United States','N/A',16,'Alcoa');
INSERT INTO Company(Location,Subsidiary,CompanyID,CompanyName) VALUES ('United States','N/A',17,'Avery Dennison');
INSERT INTO Company(Location,Subsidiary,CompanyID,CompanyName) VALUES ('United States','N/A',18,'WestRock');
INSERT INTO Company(Location,Subsidiary,CompanyID,CompanyName) VALUES ('United States','N/A',19,'Celanese');
INSERT INTO Company(Location,Subsidiary,CompanyID,CompanyName) VALUES ('Switzerland','N/A',20,'Tetra Pak');
INSERT INTO Company(Location,Subsidiary,CompanyID,CompanyName) VALUES ('United States','N/A',21,'A Fake company');
INSERT INTO Company(Location,Subsidiary,CompanyID,CompanyName) VALUES ('United States','N/A',22,'Packaging Corporation of America');
INSERT INTO Company(Location,Subsidiary,CompanyID,CompanyName) VALUES ('United States','N/A',23,'Vulcan Materials Company');
INSERT INTO Company(Location,Subsidiary,CompanyID,CompanyName) VALUES ('United States','N/A',24,'Owens-Illinois');
INSERT INTO Company(Location,Subsidiary,CompanyID,CompanyName) VALUES ('United States','N/A',25,'International Flavors & Fragrances');
INSERT INTO Company(Location,Subsidiary,CompanyID,CompanyName) VALUES ('Ireland','N/A',26,'James Hardie Industries');
INSERT INTO Company(Location,Subsidiary,CompanyID,CompanyName) VALUES ('United States','N/A',27,'USG Corporation');
INSERT INTO Company(Location,Subsidiary,CompanyID,CompanyName) VALUES ('United States','N/A',28,'Martin Marietta Materials');