INSERT INTO GeneralCategories (CategoryName) VALUES ('Metals');
INSERT INTO GeneralCategories (CategoryName) VALUES ('Polymers');
INSERT INTO GeneralCategories (CategoryName) VALUES ('Ceramics');
INSERT INTO GeneralCategories (CategoryName) VALUES ('Composites');
INSERT INTO GeneralCategories (CategoryName) VALUES ('Glass');
INSERT INTO GeneralCategories (CategoryName) VALUES ('Elastomers');
INSERT INTO GeneralCategories (CategoryName) VALUES ('Semiconductors');
INSERT INTO GeneralCategories (CategoryName) VALUES ('Natural Materials');
INSERT INTO GeneralCategories (CategoryName) VALUES ('Alloys');
INSERT INTO GeneralCategories (CategoryName) VALUES ('Conductors');
INSERT INTO GeneralCategories (CategoryName) VALUES ('Insulators');
INSERT INTO GeneralCategories (CategoryName) VALUES ('Magnetics');
INSERT INTO GeneralCategories (CategoryName) VALUES ('Superconductors');
INSERT INTO GeneralCategories (CategoryName) VALUES ('Biomedical Materials');
INSERT INTO GeneralCategories (CategoryName) VALUES ('Nanomaterials');
INSERT INTO GeneralCategories (CategoryName) VALUES ('Refractory Materials');
INSERT INTO GeneralCategories (CategoryName) VALUES ('Optical Materials');
INSERT INTO GeneralCategories (CategoryName) VALUES ('Thermal Insulators');
INSERT INTO GeneralCategories (CategoryName) VALUES ('Piezoelectric Materials');
INSERT INTO GeneralCategories (CategoryName) VALUES ('Photovoltaic Materials');
