version: '3.1'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: materials
      POSTGRES_PASSWORD: materials
      POSTGRES_DB: materialsDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
