name: Backend CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test-backend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install Python Dependencies
      run: pip install -r backend/requirements.txt

    - name: Run Pytest
      run: pytest backend/tests/ --cov=backend/app

    - name: Upload Python Coverage as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: coverage-py
        path: ./backend/coverage.xml
