name: Frontend CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test-frontend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.x' 
        npm-version: '7.x'

    - name: Change to frontend directory
      run: cd frontend

    - name: Install Dependencies
      run: npm install

    - name: Run ESLint
      run: npm run lint

    - name: Run Unit Tests with Coverage
      run: npm run test -- --coverage --testPathIgnorePatterns='integrations/'

    - name: Upload Coverage as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: coverage-js
        path: ./coverage/lcov.info
