name: Frontend CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test-frontend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.x' 
        npm-version: '7.x'

    - name: Install Dependencies
      run: npm install
      working-directory: ./frontend

    - name: Run ESLint
      run: npm run lint
      working-directory: ./frontend

    - name: Run specific test file
      run: npm test App.test.js
      working-directory: ./frontend/tests

    - name: Coveralls GitHub Action for Frontend
      uses: coverallsapp/github-action@v2.2.3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        flag-name: 'frontend'


    - name: Upload Coverage as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: coverage-js
        path: ./coverage/lcov.info
